namespace $rootnamespace$
{
    using System.Diagnostics.CodeAnalysis;

    using $rootnamespace$.Configuration;

    using NServiceBus;
	
    /// <remarks>
    /// Generated by the "StealFocus.NServiceBusExtensions" NuGet package.
    /// 
    /// A class to hold the unobtrusive message definitions. This will be picked up automatically 
    /// by NServiceBus owing to the <see cref="IWantToRunBeforeConfiguration" /> implementation.
    /// </remarks>
    [ExcludeFromCodeCoverage]
    public class UnobtrusiveConfiguration : IWantToRunBeforeConfiguration
    {
        public void Init()
        {
            Configure.Instance
                .DefiningEventsAs(MessageType.IsEvent)
                .DefiningCommandsAs(MessageType.IsCommand)
                .DefiningMessagesAs(MessageType.IsMessage);
        }
    }
}
